# Generated by Django 2.1.4 on 2018-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('stockinicial', models.IntegerField(default=0)),
                ('stockactual', models.IntegerField(default=0)),
                ('estadoactivo', models.BooleanField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
