# Generated by Django 2.1.4 on 2018-12-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20181212_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
