# Generated by Django 2.1.4 on 2019-01-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20181212_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='stockactual',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='stockinicial',
        ),
        migrations.AddField(
            model_name='inventario',
            name='numeroserie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='personal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.Personal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='estadoactivo',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estadoactivo',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
