# Generated by Django 2.1.4 on 2019-01-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20190109_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='estadoactivo',
            field=models.BooleanField(default=True),
        ),
    ]
