# Generated by Django 2.1.4 on 2019-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20190109_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='estadoactivo',
        ),
        migrations.AlterField(
            model_name='personal',
            name='estadoactivo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
