# Generated by Django 2.1.4 on 2019-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20190123_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='estadoactivo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
