# Generated by Django 2.1.4 on 2019-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_inventario_estadoactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inventario', verbose_name='Imagen'),
        ),
    ]
