# Generated by Django 2.1.4 on 2019-03-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestion', '0009_inventario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('A', 'Asignado'), ('B', 'Actividad')], max_length=1)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inventario'),
        ),
    ]
